
-- 新元宝
-- status 状态0待发布1销售中2封闭期3开放期5撤销7封闭期结束
SELECT
schemeid,pname,account,remacount,opensalebegin,opensaleend,closeterm,minapr,maxapr,remacount,blevel,status,version
FROM XXD_OPTIMIZE_SCHEME
--where schemeid='OS20160711498'
order by createdate desc

SELECT * FROM XXD_OPTIMIZE_SCHEME WHERE SCHEMEID='OS20160711498'
update XXD_OPTIMIZE_SCHEME set leastamount=100,step=100 where SCHEMEID='OS20160711498'

-- 新元宝投标记录 
-- 状态0待扣款1投标中5撤销6提前退出7到期退出 8
SELECT * FROM XXD_OPTIMIZE_USERSCHEME
where schemeid='OS20160801001'
order by addtime desc

-- 新元宝退出债权记录
SELECT * FROM XXD_OPTIMIZE_TRADE
where schemeid='SJ201607125006'




-- 新元宝自动投标 条件 已经进入锁定期 没有退出
SELECT *   FROM XXD_OPTIMIZE_SCHEME WHERE OPENSALEEND < SYSDATE AND ADD_MONTHS(OPENSALEEND,CLOSETERM) >= SYSDATE AND BLEVEL=1 AND MINAPR<=7


UPDATE XXD_OPTIMIZE_SCHEME SET MINAPR=10,MAXAPR=10 WHERE 
OPENSALEEND < SYSDATE AND ADD_MONTHS(OPENSALEEND,CLOSETERM) >= SYSDATE AND BLEVEL=1 AND MINAPR<=7




-- 新增新元宝
INSERT INTO XXD_V6_TEST.XXD_OPTIMIZE_SCHEME (ACCOUNT, BLEVEL, CLOSETERM, CREATEDATE, CREATEIP, CREATOR, DESCRIPTION,
EARNESTMAX, EARNESTPERCENT, FORFEITPERCENT, LASTMODIFY, LEASTAMOUNT, MAXAPR, MINAPR,
MODIFYDATE, MOSTAMOUNT, OPENSALEBEGIN, OPENSALEEND, PNAME,
PRESALEBEGIN, PRESALEEND, PRESALEPAYEND, 
REMACOUNT, STATUS, STEP, TENDERDESC, TYPE, VERSION, SCHEMEID)
VALUES (5000, 1, 1, SYSDATE, '127.0.0.1', 25, 'xxx',
0, 0, 1, NULL, 100, 10, 10, 
NULL, 1000000, SYSDATE, sysdate+30/(24*60), 'test', 
SYSDATE, SYSDATE,SYSDATE, 
5000, 0, 1, 1, 4, 'v2.0', 'OS20160830001');





