INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>账户明细>删除','ELEMENT','Y','FINANCE',5622,'Y');


INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>供应商返佣查询','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>门店返佣查询','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>抵扣单查询','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>供应商返佣单查询','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>门店返佣单查询','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>查看订单','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>佣金单确认','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>佣金单删除','ELEMENT','Y','FINANCE',5594,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'O2O佣金结算>佣金单打款','ELEMENT','Y','FINANCE',5594,'Y');


INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>开户管理','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>账户管理','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>制单管理','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>账户余额','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>账户明细','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>支出明细管理','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>支出明细管理>导入','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>支出明细管理>导出','ELEMENT','Y','FINANCE',5622,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'门店预付>支出明细管理>删除','ELEMENT','Y','FINANCE',5622,'Y');

INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>聚合数据管理','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>成本数据管理','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>分销差异管理','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>入账规则配置','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>档案配置','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>入账数据管理','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>入账数据汇总','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>手动入账','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>日志查询','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>字典管理','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>漏单查询','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>聚合数据管理>批量入账','ELEMENT','Y','FINANCE',5564,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>聚合数据管理>入账','ELEMENT','Y','FINANCE',5564,'Y');

update lvmama_pet.perm_permission set name='自动做账>凭证管理' where name='自动做账>入账数据管理';
update lvmama_pet.perm_permission set name='自动做账>文件上传' where name='自动做账>入账数据汇总';
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>凭证管理>凭证明细','ELEMENT','Y','FINANCE',5564,'Y'); 
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>凭证管理>汇总凭证','ELEMENT','Y','FINANCE',5564,'Y'); 

INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>EKP费用数据管理','ELEMENT','Y','FINANCE',5564,'Y');


select * from lvmama_pet.perm_permission
where name like 'sas>%'

delete from  lvmama_pet.perm_permission where permission_id=5784

select * from lvmama_pet.perm_permission
where permission_id=5594

INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'自动做账>聚合数据管理','ELEMENT','Y','FINANCE',5564,'Y');

update lvmama_pet.perm_permission set valid='Y' where permission_id=5880

INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>我的结算单','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>账单生成','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>对账单管理','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>异常处理','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>对方账单模板设置','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>对方账单处理','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>单据审核','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>任务管理','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>派单管理','ELEMENT','Y','FINANCE',6186,'Y');
INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>结算资金账户一览表','ELEMENT','Y','FINANCE',6186,'Y');

INSERT INTO lvmama_pet.perm_permission(PERMISSION_ID,NAME,TYPE,EMBED,CATEGORY,PARENT_ID,VALID )VALUES(PERM_PERMISSION_SEQ.NEXTVAL,'sas>发票管理','ELEMENT','Y','FINANCE',6186,'Y');