ALTER TABLE XXD_BORROW 
add PLEDGETYPE number(2);

comment on column XXD_BORROW.PLEDGETYPE is '抵押方式 1:GPS 2:押车';

ALTER TABLE XXD_BORROW DROP COLUMN PLEDGE;

SELECT * FROM XXD_DIC_COMMON
where typecode='BORROW_PAYMENTMETHOD'

INSERT INTO XXD_DIC_COMMON(TYPECODE,PKEY,PVALUE,PVALUE2,NOTE,STATUS,PORDER,CREATEDATE,CREATEIP,CREATOR,LASTMODIFY,MODIFYDATE)
values('BORROW_PAYMENTMETHOD', '7','一次性付息，到期还本', null,'标的还款方式', 1, 7,sysdate,'127.0.0.1', 0, 0, sysdate);

DELETE FROM XXD_DIC_COMMON WHERE TYPECODE='BORROW_PAYMENTMETHOD' AND PVALUE='7'

comment on column XXD_BORROW_FEE.feeType is  '1风险准备金 2信息咨询费 3信息服务费 4保费 5设备及保管费';

-- 字典
INSERT INTO XXD_DIC_COMMON(TYPECODE,PKEY,PVALUE,STATUS,CREATEDATE,CREATEIP,CREATOR,LASTMODIFY,MODIFYDATE)
values('OPERATETYPE', 'deduct_car_manage_fee', '设备及保管费',  1, sysdate, '127.0.0.1', 1, 1, sysdate );













      

