INSERT INTO XXD_DIC_COMMON(TYPECODE,PKEY,PVALUE,PVALUE2,STATUS,CREATEDATE,CREATEIP,CREATOR,LASTMODIFY,MODIFYDATE)
VALUES('YBP_BANK_LIST', 'icbc','中国工商银行', '/static/images/account/account-topup_12.png', 1, SYSDATE,'127.0.0.1', 0, 0, SYSDATE);

INSERT INTO XXD_DIC_COMMON(TYPECODE,PKEY,PVALUE,PVALUE2,STATUS,CREATEDATE,CREATEIP,CREATOR,LASTMODIFY,MODIFYDATE)
values('YBP_BANK_LIST', 'ccb','中国建设银行', '/static/images/account/account-topup_22.png', 1, sysdate,'127.0.0.1', 0, 0, sysdate);

INSERT INTO XXD_DIC_COMMON(TYPECODE,PKEY,PVALUE,PVALUE2,STATUS,CREATEDATE,CREATEIP,CREATOR,LASTMODIFY,MODIFYDATE)
values('YBP_BANK_LIST', 'psbc','中国邮政', '/static/images/account/account-topup_55.png', 1, sysdate,'127.0.0.1', 0, 0, sysdate);